-- infra/postgres/init.sql

CREATE SCHEMA IF NOT EXISTS main;
CREATE SCHEMA IF NOT EXISTS chat;

-- ============================================================
-- SCHEMA: main (owned by .NET API)
-- ============================================================

CREATE TABLE IF NOT EXISTS main.companies (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name           TEXT NOT NULL,
  address        TEXT NOT NULL,
  contact_number TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS main.business_units (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES main.companies(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS main.users (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id           UUID NOT NULL REFERENCES main.companies(id) ON DELETE CASCADE,
  username             TEXT NOT NULL UNIQUE,
  password_hash        TEXT NOT NULL,
  role                 TEXT NOT NULL CHECK (role IN ('Owner','Admin','Staff')),
  must_change_password BOOLEAN NOT NULL DEFAULT true,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS main.staff_profiles (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES main.companies(id) ON DELETE CASCADE,
  user_id    UUID REFERENCES main.users(id),
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS main.staff_bu (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id   UUID NOT NULL REFERENCES main.staff_profiles(id) ON DELETE CASCADE,
  bu_id      UUID NOT NULL REFERENCES main.business_units(id) ON DELETE CASCADE,
  email      TEXT NOT NULL,
  role       TEXT NOT NULL DEFAULT 'Staff' CHECK (role IN ('Admin','Staff')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (staff_id, bu_id)
);

-- MassTransit Outbox tables
CREATE TABLE IF NOT EXISTS main.inbox_state (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id           UUID NOT NULL,
  consumer_id          UUID NOT NULL,
  lock_id              UUID NOT NULL,
  row_version          BYTEA,
  received             TIMESTAMPTZ NOT NULL,
  receive_count        INT NOT NULL,
  expiration_time      TIMESTAMPTZ,
  consumed             TIMESTAMPTZ,
  delivered            TIMESTAMPTZ,
  last_sequence_number BIGINT,
  UNIQUE (message_id, consumer_id)
);

CREATE INDEX IF NOT EXISTS ix_inbox_state_delivered ON main.inbox_state (delivered);

CREATE TABLE IF NOT EXISTS main.outbox_state (
  outbox_id            UUID PRIMARY KEY,
  lock_id              UUID NOT NULL,
  row_version          BYTEA,
  created              TIMESTAMPTZ NOT NULL,
  delivered            TIMESTAMPTZ,
  last_sequence_number BIGINT
);

CREATE INDEX IF NOT EXISTS ix_outbox_state_created ON main.outbox_state (created);

CREATE TABLE IF NOT EXISTS main.outbox_message (
  sequence_number             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enqueue_time                TIMESTAMPTZ,
  sent_time                   TIMESTAMPTZ NOT NULL,
  headers                     TEXT,
  properties                  TEXT,
  inbox_message_id            UUID,
  inbox_consumer_id           UUID,
  outbox_id                   UUID,
  message_id                  UUID NOT NULL,
  content_type                VARCHAR(256) NOT NULL,
  message_type                TEXT NOT NULL,
  body                        TEXT NOT NULL,
  conversation_id             UUID,
  correlation_id              UUID,
  initiator_id                UUID,
  request_id                  UUID,
  source_address              VARCHAR(256),
  destination_address         VARCHAR(256),
  response_address            VARCHAR(256),
  fault_address               VARCHAR(256),
  expiration_time             TIMESTAMPTZ,
  FOREIGN KEY (inbox_message_id, inbox_consumer_id) REFERENCES main.inbox_state (message_id, consumer_id),
  FOREIGN KEY (outbox_id) REFERENCES main.outbox_state (outbox_id)
);

CREATE INDEX IF NOT EXISTS ix_outbox_message_enqueue_time ON main.outbox_message (enqueue_time);
CREATE INDEX IF NOT EXISTS ix_outbox_message_expiration_time ON main.outbox_message (expiration_time);
CREATE UNIQUE INDEX IF NOT EXISTS ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence ON main.outbox_message (inbox_message_id, inbox_consumer_id, sequence_number);
CREATE UNIQUE INDEX IF NOT EXISTS ix_outbox_message_outbox_id_sequence_number ON main.outbox_message (outbox_id, sequence_number);

CREATE TABLE IF NOT EXISTS main.chat_permissions (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id   UUID NOT NULL REFERENCES main.staff_profiles(id) ON DELETE CASCADE,
  bu_id      UUID NOT NULL REFERENCES main.business_units(id) ON DELETE CASCADE,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (staff_id, bu_id)
);

-- ============================================================
-- SCHEMA: chat (owned by Go chat service)
-- ============================================================

CREATE TABLE IF NOT EXISTS chat.workspaces (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bu_id      UUID NOT NULL UNIQUE,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat.workspace_members (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES chat.workspaces(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL,
  role         TEXT NOT NULL CHECK (role IN ('admin','member')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, user_id)
);

CREATE TABLE IF NOT EXISTS chat.messages (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES chat.workspaces(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL,
  display_name TEXT NOT NULL,
  content      TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_messages_workspace_created
  ON chat.messages(workspace_id, created_at DESC);
